version: "3.9"

# services:
#   mailhog:
#     image: mailhog/mailhog
#     ports:
#       - "1025:1025" # SMTP port
#       - "8025:8025" # Web UI port

services:
  dovecot:
    image: dovecot/dovecot
    volumes:
      - ./dovecot/config:/etc/dovecot
    ports:
      - "143:143" # IMAP port
      - "110:110" # POP3 port
    environment:
      - USER1=john@example.com
      - PASS1=password
      - USER2=jane@example.com
      - PASS2=securepassword

  roundcube:
    image: roundcube/roundcubemail
    restart: always
    volumes:
      - ./roundcube/config:/var/www/html/config
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_USER=root
      - ROUNDCUBEMAIL_DB_PASSWORD=mysecretpassword
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://dovecot
      - ROUNDCUBEMAIL_SMTP_SERVER=smtp
      - ROUNDCUBEMAIL_IMAP_SERVER=dovecot
    ports:
      - "808:80"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: roundcubemail
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcubepassword
    volumes:
      - ./mysql/data:/var/lib/mysql
