version: "3.9"

services:
  zap:
    image: kamranahmed/local-ses:latest
    ports:
      - "8182:8182"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M