version: "3.9"

services:
  zap:
    image: softwaresecurityproject/zap-stable
    environment:
      - ZAP_PORT=8080
      - ZAP_USER=admin
      - ZAP_PASSWORD=admin
    ports:
      - "8980:8080"
      - "8990:8090"
    command: >
      sh -c "zap-webswing.sh"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M