version: '3'
services:
  greenmail:
    image: greenmail/standalone
    ports:
      - "3025:3025"
      - "3110:3110"
      - "3143:3143"
    environment:
      - GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=test_user:password
